const router = require("express").Router();
const { authRequired } = require("../middlewares/auth");
const marketplaceController = require("../controllers/marketplace.controller");

router.get("/", authRequired, marketplaceController.getPosts);
router.get("/mine", authRequired, marketplaceController.getMyPosts);
router.post("/ai-search", authRequired, marketplaceController.aiSearchPosts);
router.get("/favorites/mine", authRequired, marketplaceController.getMyFavorites);
router.get("/requests/mine", authRequired, marketplaceController.getMyRequests);
router.get("/requests/to-me", authRequired, marketplaceController.getRequestsToMe);
router.get("/analytics/seller", authRequired, marketplaceController.getSellerAnalytics);
router.get("/reports/seller.csv", authRequired, marketplaceController.getSellerReportCsv);
router.get("/reports/seller.pdf", authRequired, marketplaceController.getSellerReportPdf);
router.post("/favorites/:postId/toggle", authRequired, marketplaceController.toggleFavorite);
router.get("/cart", authRequired, marketplaceController.getMyCart);
router.post("/cart/items", authRequired, marketplaceController.addCartItem);
router.post("/cart/checkout", authRequired, marketplaceController.checkoutCart);
router.delete("/cart", authRequired, marketplaceController.clearCart);
router.delete("/cart/items/:itemId", authRequired, marketplaceController.removeCartItem);
router.get("/:id", authRequired, marketplaceController.getPostById);
router.post("/", authRequired, marketplaceController.createPost);
router.post("/:id/requests", authRequired, marketplaceController.createRequest);
router.patch("/:id", authRequired, marketplaceController.updatePost);
router.patch("/:id/status", authRequired, marketplaceController.updatePostStatus);
router.patch("/requests/:requestId", authRequired, marketplaceController.updateMyRequest);
router.patch("/requests/:requestId/reoffer", authRequired, marketplaceController.reofferRequest);
router.patch("/requests/:requestId/decision", authRequired, marketplaceController.decideRequest);
router.delete("/:id", authRequired, marketplaceController.deletePost);
router.delete("/requests/:requestId", authRequired, marketplaceController.deleteMyRequest);
router.post("/:id/messages", authRequired, marketplaceController.createMessage);

module.exports = router;
