export const theme = {
  colors: {
    bg: "#f3f7ff",
    bgAccent: "#e6efff",
    surface: "#ffffff",
    surfaceAlt: "#eef4ff",
    surfaceSoft: "#f8fbff",
    primary: "#2f5cff",
    primaryDeep: "#183fc9",
    primarySoft: "#dfe7ff",
    accent: "#10b981",
    accentSoft: "#dff8ef",
    teal: "#0ea5a8",
    tealSoft: "#d9f6f4",
    gold: "#f59e0b",
    goldSoft: "#fff1cf",
    rose: "#ef4444",
    roseSoft: "#ffe2e0",
    text: "#0f172a",
    textMuted: "#5f6c85",
    border: "#d8e0f0",
    danger: "#d92d20",
    warningBg: "#fff1cf",
    warningText: "#8a6116",
    infoBg: "#deecff",
    infoText: "#184a9b",
    successBg: "#dff8ef",
    successText: "#136548",
    neutralBg: "#e9edf5",
    neutralText: "#3f4b63",
    shadow: "#15203a",
  },
  radius: {
    sm: 10,
    md: 14,
    lg: 20,
    xl: 28,
    pill: 999,
  },
  spacing: {
    xs: 6,
    sm: 10,
    md: 14,
    lg: 20,
  },
  shadow: {
    soft: {
      shadowColor: "#15203a",
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.08,
      shadowRadius: 18,
      elevation: 4,
    },
    card: {
      shadowColor: "#15203a",
      shadowOffset: { width: 0, height: 10 },
      shadowOpacity: 0.1,
      shadowRadius: 22,
      elevation: 5,
    },
  },
};
